### PR TITLE
Print error messages when a flavor not found

### LINKED ISSUE #2453: Buck should print a warning message for non-exist flavors
A repro can be found in #2399. A wrong build command `buck build :Test#dwarf-with-dsym,iphoneos-arm64` (which should be `buck build :Test#dwarf-and-dsym,iphoneos-arm64`) was entered but buck does not complain about that.
Make buck display a warning.

### PR DESCRIPTION
**Pull request by v-jizhang**
Fixed #2453 and #2399 
Test - Build with a non-exist flavor will print error messages:
```
$buck build :MyApp#dwarf-with-dsym,iphoneos-arm64

The following flavor(s) are not supported on target //:MyApp#dwarf-with-dsym,iphoneos-arm64:
dwarf-with-dsym

Available flavors are:
iphoneos-arm64


- Please check the spelling of the flavor(s).
- If the spelling is correct, please check that the related SDK has been installed.
```

### CODE REVIEW

File: src/com/facebook/buck/apple/AppleBinaryDescription.java [hunk 1]
```diff
@@ -178,24 +178,28 @@ public AppleBinaryDescription(
...
     if (thinFlavorSets.size() > 0) {
       return Iterables.all(
-          thinFlavorSets,
-          inputFlavors -> cxxBinaryFlavored.hasFlavors(inputFlavors, toolchainTargetConfiguration));
+        thinFlavorSets,
+        inputFlavors -> cxxBinaryFlavored.hasFlavors(inputFlavors, toolchainTargetConfiguration));
     } else {
-      return cxxBinaryFlavored.hasFlavors(delegateFlavors, toolchainTargetConfiguration);
+      return cxxBinaryFlavored.hasFlavors(ImmutableSet.<Flavor>copyOf(unmatchedFlavors),
+        toolchainTargetConfiguration);
```
Comment (zpao) [inline src/com/facebook/buck/apple/AppleBinaryDescription.java:202]: Looks like this will match style more closely

```suggestion
      return cxxBinaryFlavored.hasFlavors(
        ImmutableSet.<Flavor>copyOf(unmatchedFlavors),
        toolchainTargetConfiguration);
```

File: src/com/facebook/buck/swift/SwiftLibraryDescription.java [hunk 2]
```diff
@@ -500,6 +500,16 @@ public static boolean isSwiftTarget(BuildTarget buildTarget) {
         .getUnresolvedCxxPlatforms();
   }
 
+  public ImmutableSet<Flavor> getSupportedFlavors(
+    ImmutableSet<Flavor> flavors, TargetConfiguration toolchainTargetConfiguration) {
```
Comment (zpao) [inline src/com/facebook/buck/swift/SwiftLibraryDescription.java:504]: 4 spaces for function definition

File: src/com/facebook/buck/apple/AppleBinaryDescription.java [hunk 3]
```diff
@@ -178,24 +178,28 @@ public AppleBinaryDescription(
...
     ImmutableSet<Flavor> delegateFlavors =
-        ImmutableSet.copyOf(Sets.difference(flavors, NON_DELEGATE_FLAVORS));
-    if (swiftDelegate
-        .map(swift -> swift.hasFlavors(delegateFlavors, toolchainTargetConfiguration))
-        .orElse(false)) {
+      ImmutableSet.copyOf(Sets.difference(flavors, NON_DELEGATE_FLAVORS));
+    ImmutableSet<Flavor> supportedDelegateFlavors = swiftDelegate
+      .map(swift -> swift.getSupportedFlavors(delegateFlavors, toolchainTargetConfiguration))
+      .orElse(ImmutableSet.<Flavor>of());
+    unmatchedFlavors = Sets.difference(unmatchedFlavors, supportedDelegateFlavors);
```
Comment (zpao) [inline src/com/facebook/buck/apple/AppleBinaryDescription.java:190]: Would it be valuable to just make this an immutable set now, rather than potentially make 2 later?
